### ISSUE TITLE
Bugged gravity when walking towards a wall[BUG]

### ISSUE THREAD

**Issue by WizardlyBump17** [hytopiagg/sdk#4]
When you walk towards a wall you slowly fall. It is better to understand it if  you watch the video:

https://github.com/user-attachments/assets/5633f9f3-da98-4f25-828f-543087912316

I used the payload-game example, but it happens on all examples.

**Comment by iamarkdev** [comment]
Ty ty! Noted, will get this resolved in a future update

**Comment by iamarkdev** [comment]
Resolved in version release 0.1.47 👍
